# Generated by Django 4.0 on 2023-02-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_work_alter_review_name_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.master'),
        ),
    ]
