# Generated by Django 4.0 on 2023-02-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0010_alter_beauty_price'),
        ('masters', '0005_work_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='text',
        ),
        migrations.AddField(
            model_name='work',
            name='procedure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beauty.beauty'),
        ),
    ]
