# Generated by Django 4.0 on 2023-02-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_remove_work_text_work_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
