# Generated by Django 4.0 on 2023-02-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0013_beauty_procedures'),
        ('masters', '0007_alter_master_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.typebeauty'),
        ),
    ]
