# Generated by Django 4.0 on 2023-02-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0010_remove_master_uslugi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('master', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.master')),
            ],
        ),
    ]
