# Generated by Django 4.0 on 2023-02-26 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0013_beauty_procedures'),
        ('zapis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapis',
            name='usluga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beauty.beauty'),
        ),
    ]
