# Generated by Django 4.0 on 2023-02-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_alter_review_name_alter_review_rate_and_more'),
        ('beauty', '0014_typebeauty_image'),
        ('zapis', '0002_zapis_usluga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapis',
            name='date',
            field=models.DateTimeField(verbose_name='Выберите дату и время'),
        ),
        migrations.AlterField(
            model_name='zapis',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.master', verbose_name='Выберите мастера'),
        ),
        migrations.AlterField(
            model_name='zapis',
            name='usluga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beauty.beauty', verbose_name='Выберите процедуру'),
        ),
    ]
