# Generated by Django 4.0 on 2023-02-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_alter_review_name_alter_review_rate_and_more'),
        ('zapis', '0003_alter_zapis_date_alter_zapis_master_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(unique_for_date=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.master')),
            ],
        ),
        migrations.DeleteModel(
            name='Zapis',
        ),
    ]
