# Generated by Django 4.0 on 2023-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0005_remove_date_datetime_date_date_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default='2023-03-03'),
        ),
    ]
