# Generated by Django 4.0 on 2023-03-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0007_alter_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('request', models.TextField(blank=True)),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateField()),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
