# Generated by Django 4.0 on 2023-03-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0008_appointment_delete_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('MO', 'MO'), ('TU', 'TU'), ('WE', 'WE'), ('TH', 'TH'), ('FR', 'FR'), ('SA', 'SA'), ('SU', 'SU')], max_length=2, verbose_name='День недели')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='request',
        ),
    ]
