# Generated by Django 4.0 on 2023-03-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0009_bookingtime_remove_appointment_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='days',
            field=models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednasday'), ('TH', 'Thursaday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sundat')], max_length=10, verbose_name='День недели'),
        ),
    ]
