# Generated by Django 4.0 on 2023-03-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0010_alter_bookingtime_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednasday', 'Wednasday'), ('Thursaday', 'Thursaday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, verbose_name='День недели'),
        ),
    ]
