# Generated by Django 4.0 on 2023-03-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0014_typebeauty_image'),
        ('masters', '0011_alter_review_name_alter_review_rate_and_more'),
        ('zapis', '0011_alter_bookingtime_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.master'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beauty.beauty'),
        ),
    ]
