# Generated by Django 4.0 on 2023-03-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0012_appointment_master_appointment_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='accepted',
        ),
    ]
