# Generated by Django 4.0 on 2023-03-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0013_remove_appointment_accepted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='sent_date',
        ),
    ]
