# Generated by Django 4.0 on 2023-03-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0015_alter_appointment_accepted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='end_time',
            field=models.DurationField(),
        ),
    ]
