# Generated by Django 4.0 on 2023-03-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0017_alter_bookingtime_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='end_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='bookingtime',
            name='start_time',
            field=models.DurationField(),
        ),
    ]
