# Generated by Django 4.0 on 2023-03-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0020_alter_bookingtime_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=10)),
            ],
        ),
    ]
