# Generated by Django 4.0 on 2023-03-02 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0021_bookingdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='days',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapis.bookingdays'),
        ),
    ]
