# Generated by Django 4.0 on 2023-03-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0027_remove_bookingtime_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zapis.bookingdays'),
        ),
        migrations.AlterField(
            model_name='bookingtime',
            name='start_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zapis.bookingslots'),
        ),
    ]
