# Generated by Django 4.0 on 2023-03-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0028_alter_bookingtime_days_alter_bookingtime_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='slot',
            new_name='time',
        ),
    ]
