# Generated by Django 4.0 on 2023-03-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0030_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
    ]
