# Generated by Django 4.0 on 2023-03-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0031_remove_appointment_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Введите свое имя'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Введите свою фамилию'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Введите номер телефона без 8'),
        ),
    ]
