# Generated by Django 4.0 on 2023-02-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beauty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedures', models.CharField(choices=[('br', 'Брови'), ('la', 'Ресницы'), ('na', 'Ногти'), ('ha', 'Волосы')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='movie/images/')),
            ],
        ),
    ]
