# Generated by Django 4.0 on 2023-02-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beauty',
            name='image',
            field=models.ImageField(upload_to='beauty/images/'),
        ),
        migrations.AlterField(
            model_name='beauty',
            name='procedures',
            field=models.CharField(choices=[('Брови', 'Брови'), ('Ресницы', 'Ресницы'), ('Ногти', 'Ногти'), ('Волосы', 'Волосы')], max_length=15),
        ),
    ]
