# Generated by Django 4.0 on 2023-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_alter_beauty_image_alter_beauty_procedures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('image', models.ImageField(upload_to='beauty/images/masters')),
            ],
        ),
        migrations.AlterField(
            model_name='beauty',
            name='image',
            field=models.ImageField(upload_to='beauty/images/uslugi'),
        ),
    ]
