# Generated by Django 4.0 on 2023-02-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_master_alter_beauty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='master',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='image',
            field=models.ImageField(upload_to='beauty/images'),
        ),
    ]
