# Generated by Django 4.0 on 2023-02-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
