# Generated by Django 4.0 on 2023-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0007_delete_master_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='beauty',
            name='price',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
