# Generated by Django 4.0 on 2023-02-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0008_beauty_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beauty',
            name='price',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
