# Generated by Django 4.0 on 2023-02-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0010_alter_beauty_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beauty',
            name='procedures',
        ),
    ]
