# Generated by Django 4.0 on 2023-02-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0011_remove_beauty_procedures'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeBeauty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
            ],
        ),
    ]
