# Generated by Django 4.0 on 2023-02-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0012_typebeauty'),
    ]

    operations = [
        migrations.AddField(
            model_name='beauty',
            name='procedures',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='beauty.typebeauty'),
        ),
    ]
