# Generated by Django 4.0 on 2023-02-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0013_beauty_procedures'),
    ]

    operations = [
        migrations.AddField(
            model_name='typebeauty',
            name='image',
            field=models.ImageField(blank=True, upload_to='beauty/images/types'),
        ),
    ]
